import type { FC } from 'react';
import CodeSnippet from '../components/ui/CodeSnippet';
import SEO from '../components/seo/SEO';
import FAQ from '../components/docs/FAQ';
import { Link } from 'react-router-dom';

const DocsTroubleshooting: FC = () => {
  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        name: 'Home',
        item: 'https://parapetai.com/',
      },
      {
        '@type': 'ListItem',
        position: 2,
        name: 'Documentation',
        item: 'https://parapetai.com/docs',
      },
      {
        '@type': 'ListItem',
        position: 3,
        name: 'Troubleshooting',
        item: 'https://parapetai.com/docs/troubleshooting',
      },
    ],
  };

  const faqItems = [
    {
      question: 'How do I check if ParapetAI is running correctly?',
      answer: 'Use the /health endpoint: curl http://localhost:8000/health. It should return {"statusCode":200,"data":{"isValid":true}}. If it fails, check container logs and ensure the bootstrap environment variables are set correctly.',
    },
    {
      question: 'Why am I getting invalid_parapet_api_key errors?',
      answer: 'This means your Authorization Bearer token is missing or incorrect. Verify you\'re using the service token generated by the CLI (PARAPET_SERVICE_<LABEL>_TOKEN). Check that the token matches what\'s in your encrypted bootstrap configuration.',
    },
    {
      question: 'What does drift_violation mean?',
      answer: 'A drift_violation occurs when you request a model that isn\'t configured for your service token\'s allowed routes. Check your parapet.yaml to ensure the model name matches exactly, and that your service\'s allowed_routes includes the route with that model.',
    },
    {
      question: 'How do I debug budget issues?',
      answer: 'Check telemetry logs for budget_exceeded events. Verify your daily budget caps in the configuration. Budgets reset at midnight UTC. You can also check webhook events for budget_spend_today_usd values to see current spending.',
    },
    {
      question: 'Why are my requests slow?',
      answer: 'Check if caching is enabled and working (look for cache_hit in logs). Review provider_latency_ms in logs to see if the upstream provider is slow. Check retry_count to see if retries are happening. Consider enabling caching for repeated requests.',
    },
    {
      question: 'How do I verify webhook signatures?',
      answer: 'Compute HMAC-SHA256 of the raw request body using your webhook secret. Compare it with the X-Parapet-Signature header (after removing "sha256=" prefix) using timing-safe comparison. See the API Reference for code examples.',
    },
  ];

  return (
    <>
      <SEO
        title="Troubleshooting - ParapetAI"
        description="Comprehensive troubleshooting guide for ParapetAI including common errors, debugging tips, log interpretation, and performance optimization. Learn how to diagnose and fix issues with your LLM gateway."
        keywords="ParapetAI troubleshooting, LLM gateway debugging, error resolution, log interpretation, performance issues, API gateway problems"
        canonical="https://parapetai.com/docs/troubleshooting"
        structuredData={breadcrumbSchema}
      />
      <div className="mx-auto max-w-6xl px-4 py-16 sm:py-24">
        <header className="max-w-3xl">
          <h1 className="text-4xl font-semibold tracking-tight text-text sm:text-5xl">Troubleshooting</h1>
          <p className="mt-4 text-base leading-7 text-muted">
            Common issues, debugging tips, and solutions for ParapetAI. Learn how to diagnose problems, interpret logs, and optimize performance.
          </p>
        </header>

        <section className="mt-12">
          <h2 className="text-2xl font-semibold text-text">Common Errors</h2>

          <div className="mt-6 space-y-8">
            <div>
              <h3 className="text-lg font-semibold text-text">Authentication Failures</h3>
              
              <div className="mt-4">
                <h4 className="text-base font-semibold text-text">invalid_parapet_api_key (401)</h4>
                <p className="mt-2 text-sm text-muted">
                  The Authorization Bearer token is missing, malformed, or doesn't match any configured service token.
                </p>
                <div className="mt-4 space-y-3">
                  <div>
                    <p className="text-sm font-medium text-text">Solutions:</p>
                    <ul className="mt-2 space-y-1 text-sm text-muted list-disc list-inside">
                      <li>Verify the Authorization header format: <code>Authorization: Bearer &lt;token&gt;</code></li>
                      <li>Check that you're using the service token printed by the CLI (PARAPET_SERVICE_&lt;LABEL&gt;_TOKEN)</li>
                      <li>Ensure the token matches what's in your encrypted bootstrap configuration</li>
                      <li>Rebuild the configuration if you regenerated service tokens</li>
                    </ul>
                  </div>
                  <CodeSnippet
                    title="Verify Token Format"
                    lines={[
                      'curl -v http://localhost:8000/v1/chat/completions \\',
                      '  -H "Authorization: Bearer YOUR_TOKEN_HERE" \\',
                      '  -H "Content-Type: application/json" \\',
                      '  -d \'{"model":"gpt-4o-mini","messages":[{"role":"user","content":"test"}]}\'',
                    ]}
                  />
                </div>
              </div>

              <div className="mt-6">
                <h4 className="text-base font-semibold text-text">invalid_openai_api_key (401)</h4>
                <p className="mt-2 text-sm text-muted">
                  The provider API key configured for the route is invalid or expired.
                </p>
                <div className="mt-4 space-y-3">
                  <div>
                    <p className="text-sm font-medium text-text">Solutions:</p>
                    <ul className="mt-2 space-y-1 text-sm text-muted list-disc list-inside">
                      <li>Verify your OpenAI API key is valid and has sufficient credits</li>
                      <li>Check the environment variable referenced in provider_key_ref</li>
                      <li>Ensure the key is correctly set when building the configuration</li>
                      <li>For local providers, verify the endpoint is accessible</li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>

            <div>
              <h3 className="text-lg font-semibold text-text">Policy Violations</h3>
              
              <div className="mt-4">
                <h4 className="text-base font-semibold text-text">drift_violation (400)</h4>
                <p className="mt-2 text-muted text-sm">
                  The requested model doesn't match any route configured for your service token, or drift_strict is enabled and the model isn't explicitly allowed.
                </p>
                <div className="mt-4 space-y-3">
                  <div>
                    <p className="text-sm font-medium text-text">Solutions:</p>
                    <ul className="mt-2 space-y-1 text-sm text-muted list-disc list-inside">
                      <li>Verify the model name matches exactly (case-sensitive) with your route configuration</li>
                      <li>Check that your service's allowed_routes includes a route with the requested model</li>
                      <li>Review your parapet.yaml to ensure the model is configured correctly</li>
                      <li>If drift_strict is enabled, you must use the exact model specified in the route</li>
                    </ul>
                  </div>
                  <CodeSnippet
                    title="Check Configuration"
                    lines={[
                      '# In parapet.yaml, verify:',
                      'routes:',
                      '  - name: acme-chat',
                      '    provider:',
                      '      model: gpt-4o-mini  # Must match request exactly',
                      '',
                      'services:',
                      '  - label: myapp',
                      '    allowed_routes: [acme-chat]  # Must include the route',
                    ]}
                  />
                </div>
              </div>

              <div className="mt-6">
                <h4 className="text-base font-semibold text-text">budget_exceeded (429)</h4>
                <p className="mt-2 text-sm text-muted">
                  The route or tenant has exceeded its daily budget cap.
                </p>
                <div className="mt-4 space-y-3">
                  <div>
                    <p className="text-sm font-medium text-text">Solutions:</p>
                    <ul className="mt-2 space-y-1 text-sm text-muted list-disc list-inside">
                      <li>Check webhook events or telemetry for current spend (budget_spend_today_usd)</li>
                      <li>Wait until midnight UTC for daily budgets to reset</li>
                      <li>Increase budget_daily_usd in route policy or daily_usd_cap in tenant configuration</li>
                      <li>Rebuild and redeploy configuration after changes</li>
                    </ul>
                  </div>
                  <CodeSnippet
                    title="Increase Budget"
                    lines={[
                      '# In parapet.yaml:',
                      'routes:',
                      '  - name: acme-chat',
                      '    policy:',
                      '      budget_daily_usd: 20.0  # Increase from current value',
                      '',
                      '# Or increase tenant cap:',
                      'tenants:',
                      '  - name: acme',
                      '    spend:',
                      '      daily_usd_cap: 100.0  # Increase from current value',
                    ]}
                  />
                </div>
              </div>

              <div className="mt-6">
                <h4 className="text-base font-semibold text-text">max_tokens_in_exceeded (400)</h4>
                <p className="mt-2 text-sm text-muted">
                  The input token count exceeds the route's max_tokens_in policy limit.
                </p>
                <div className="mt-4 space-y-3">
                  <div>
                    <p className="text-sm font-medium text-text">Solutions:</p>
                    <ul className="mt-2 space-y-1 text-sm text-muted list-disc list-inside">
                      <li>Reduce the size of your input messages</li>
                      <li>Increase max_tokens_in in the route policy</li>
                      <li>Remove unnecessary context or system messages</li>
                    </ul>
                  </div>
                </div>
              </div>

              <div className="mt-6">
                <h4 className="text-base font-semibold text-text">redaction_blocked (400)</h4>
                <p className="mt-2 text-sm text-muted">
                  Sensitive data was detected in the request and redaction mode is set to "block".
                </p>
                <div className="mt-4 space-y-3">
                  <div>
                    <p className="text-sm font-medium text-text">Solutions:</p>
                    <ul className="mt-2 space-y-1 text-sm text-muted list-disc list-inside">
                      <li>Remove sensitive data (emails, API keys, IPs, phone numbers) from the request</li>
                      <li>Change redaction mode to "warn" to scrub instead of block</li>
                      <li>Review redaction patterns in your route policy</li>
                      <li>Check webhook events to see what was detected</li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>

            <div>
              <h3 className="text-lg font-semibold text-text">Request Validation Errors</h3>
              
              <div className="mt-4">
                <h4 className="text-base font-semibold text-text">invalid_json (400)</h4>
                <p className="mt-2 text-sm text-muted">
                  The request body is not valid JSON.
                </p>
                <div className="mt-4 space-y-3">
                  <div>
                    <p className="text-sm font-medium text-text">Solutions:</p>
                    <ul className="mt-2 space-y-1 text-sm text-muted list-disc list-inside">
                      <li>Verify JSON syntax is correct (use a JSON validator)</li>
                      <li>Ensure Content-Type header is application/json</li>
                      <li>Check for unescaped quotes or special characters</li>
                    </ul>
                  </div>
                </div>
              </div>

              <div className="mt-6">
                <h4 className="text-base font-semibold text-text">invalid_body (400)</h4>
                <p className="mt-2 text-sm text-muted">
                  Required fields are missing (model, messages for chat completions, or input for embeddings).
                </p>
                <div className="mt-4 space-y-3">
                  <div>
                    <p className="text-sm font-medium text-text">Solutions:</p>
                    <ul className="mt-2 space-y-1 text-sm text-muted list-disc list-inside">
                      <li>Ensure model field is present and non-empty</li>
                      <li>For chat completions, include messages array with at least one message</li>
                      <li>For embeddings, include input field (string or array of strings)</li>
                      <li>Check that parameter names match OpenAI API format exactly</li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>

            <div>
              <h3 className="text-lg font-semibold text-text">Upstream Provider Errors</h3>
              
              <div className="mt-4">
                <h4 className="text-base font-semibold text-text">upstream_error (502)</h4>
                <p className="mt-2 text-sm text-muted">
                  The upstream provider (OpenAI or local) returned an error after all retries were exhausted.
                </p>
                <div className="mt-4 space-y-3">
                  <div>
                    <p className="text-sm font-medium text-text">Solutions:</p>
                    <ul className="mt-2 space-y-1 text-sm text-muted list-disc list-inside">
                      <li>Check provider API status and rate limits</li>
                      <li>Verify your provider API key has sufficient credits</li>
                      <li>Review retry configuration - increase max_attempts or adjust backoff if needed</li>
                      <li>Check logs for the specific provider error message</li>
                      <li>For local providers, verify the endpoint is running and accessible</li>
                    </ul>
                  </div>
                  <CodeSnippet
                    title="Check Provider Status"
                    lines={[
                      '# Test OpenAI API directly:',
                      'curl https://api.openai.com/v1/models \\',
                      '  -H "Authorization: Bearer $OPENAI_API_KEY"',
                      '',
                      '# Check local provider:',
                      'curl http://localhost:11434/v1/models',
                    ]}
                  />
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="mt-12">
          <h2 className="text-2xl font-semibold text-text">Debugging Tips</h2>

          <div className="mt-6 space-y-8">
            <div>
              <h3 className="text-lg font-semibold text-text">Check Runtime Health</h3>
              <p className="mt-2 text-sm text-muted">
                Verify the runtime is running and can decrypt the bootstrap configuration.
              </p>
              <CodeSnippet
                title="Health Check"
                lines={[
                  'curl http://localhost:8000/health',
                  '',
                  '# Expected response:',
                  '# {"statusCode":200,"data":{"isValid":true}}',
                ]}
              />
              <p className="mt-3 text-sm text-muted">
                If this fails, check container logs and ensure PARAPET_MASTER_KEY and PARAPET_BOOTSTRAP_STATE environment variables are set correctly.
              </p>
            </div>

            <div>
              <h3 className="text-lg font-semibold text-text">Verify Configuration</h3>
              <p className="mt-2 text-sm text-muted">
                Use the CLI to validate your configuration before building the bootstrap.
              </p>
              <CodeSnippet
                title="Validate Configuration"
                lines={[
                  'npx @parapetai/cli@latest build-config \\',
                  '  --file parapet.yaml \\',
                  '  --non-interactive \\',
                  '  --out .env',
                  '',
                  '# The CLI will report any schema errors or missing references',
                ]}
              />
            </div>

            <div>
              <h3 className="text-lg font-semibold text-text">Test Service Tokens</h3>
              <p className="mt-2 text-sm text-muted">
                Verify your service token works with a simple request.
              </p>
              <CodeSnippet
                title="Test Token"
                lines={[
                  'export PARAPET_TOKEN="your-service-token-here"',
                  '',
                  'curl -X POST http://localhost:8000/v1/chat/completions \\',
                  '  -H "Authorization: Bearer $PARAPET_TOKEN" \\',
                  '  -H "Content-Type: application/json" \\',
                  '  -d \'{',
                  '    "model": "gpt-4o-mini",',
                  '    "messages": [{"role": "user", "content": "test"}]',
                  '  }\'',
                ]}
              />
            </div>

            <div>
              <h3 className="text-lg font-semibold text-text">Validate Webhook Signatures</h3>
              <p className="mt-2 text-sm text-muted">
                Test webhook signature verification to ensure your receiver works correctly.
              </p>
              <CodeSnippet
                title="Signature Test"
                lines={[
                  'import crypto from "node:crypto";',
                  '',
                  'const secret = "your-webhook-secret";',
                  'const body = \'{"timestamp":"2024-01-15T10:30:00.000Z",...}\';',
                  '',
                  'const signature = crypto',
                  '  .createHmac("sha256", secret)',
                  '  .update(body)',
                  '  .digest("hex");',
                  '',
                  'console.log("sha256=" + signature);',
                  '# Compare with X-Parapet-Signature header',
                ]}
              />
            </div>
          </div>
        </section>

        <section className="mt-12">
          <h2 className="text-2xl font-semibold text-text">Log Interpretation</h2>
          <p className="mt-4 text-sm leading-7 text-muted">
            ParapetAI logs structured information about every request. Understanding log format helps diagnose issues.
          </p>

          <div className="mt-6 space-y-8">
            <div>
              <h3 className="text-lg font-semibold text-text">Log Format</h3>
              <p className="mt-2 text-sm text-muted">
                Logs use key=value format for easy parsing. Each log line represents a single event.
              </p>
              <CodeSnippet
                title="Example Log Lines"
                lines={[
                  'request_ok endpoint=chat_completions tenant=acme route=acme-chat service=myapp model=gpt-4o-mini http_latency_ms=1250 provider_latency_ms=1200 est_cost_usd=0.000012 final_cost_usd=0.000011 tokens_in=9 tokens_out=12 cache_enabled=true cache_hit=false',
                  '',
                  'policy_block endpoint=chat_completions tenant=acme route=acme-chat reason=budget_exceeded',
                  '',
                  'provider_error endpoint=chat_completions tenant=acme route=acme-chat reason=upstream_error provider=OpenAI status=429 code=rate_limit_exceeded',
                ]}
              />
            </div>

            <div>
              <h3 className="text-lg font-semibold text-text">Key Log Fields</h3>
              <div className="mt-4 overflow-x-auto rounded-lg ring-1 ring-black/10">
                <table className="min-w-full text-left">
                  <thead className="bg-black/5">
                    <tr>
                      <th className="px-4 py-2 font-medium text-text">Field</th>
                      <th className="px-4 py-2 font-medium text-text">Description</th>
                    </tr>
                  </thead>
                  <tbody className="align-top">
                    <tr className="border-t border-black/10">
                      <td className="px-4 py-3"><code>endpoint</code></td>
                      <td className="px-4 py-3 text-muted">API endpoint: chat_completions or embeddings</td>
                    </tr>
                    <tr className="border-t border-black/10">
                      <td className="px-4 py-3"><code>tenant</code></td>
                      <td className="px-4 py-3 text-muted">Tenant identifier</td>
                    </tr>
                    <tr className="border-t border-black/10">
                      <td className="px-4 py-3"><code>route</code></td>
                      <td className="px-4 py-3 text-muted">Route name</td>
                    </tr>
                    <tr className="border-t border-black/10">
                      <td className="px-4 py-3"><code>service</code></td>
                      <td className="px-4 py-3 text-muted">Service label</td>
                    </tr>
                    <tr className="border-t border-black/10">
                      <td className="px-4 py-3"><code>reason</code></td>
                      <td className="px-4 py-3 text-muted">Error or block reason (if applicable)</td>
                    </tr>
                    <tr className="border-t border-black/10">
                      <td className="px-4 py-3"><code>http_latency_ms</code></td>
                      <td className="px-4 py-3 text-muted">Total request latency from client to response</td>
                    </tr>
                    <tr className="border-t border-black/10">
                      <td className="px-4 py-3"><code>provider_latency_ms</code></td>
                      <td className="px-4 py-3 text-muted">Time spent calling upstream provider</td>
                    </tr>
                    <tr className="border-t border-black/10">
                      <td className="px-4 py-3"><code>est_cost_usd</code></td>
                      <td className="px-4 py-3 text-muted">Pre-call cost estimate</td>
                    </tr>
                    <tr className="border-t border-black/10">
                      <td className="px-4 py-3"><code>final_cost_usd</code></td>
                      <td className="px-4 py-3 text-muted">Actual cost after completion</td>
                    </tr>
                    <tr className="border-t border-black/10">
                      <td className="px-4 py-3"><code>tokens_in</code></td>
                      <td className="px-4 py-3 text-muted">Input tokens consumed</td>
                    </tr>
                    <tr className="border-t border-black/10">
                      <td className="px-4 py-3"><code>tokens_out</code></td>
                      <td className="px-4 py-3 text-muted">Output tokens generated</td>
                    </tr>
                    <tr className="border-t border-black/10">
                      <td className="px-4 py-3"><code>cache_hit</code></td>
                      <td className="px-4 py-3 text-muted">Whether response was served from cache</td>
                    </tr>
                    <tr className="border-t border-black/10">
                      <td className="px-4 py-3"><code>cache_size</code></td>
                      <td className="px-4 py-3 text-muted">Current cache entry count</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div>
              <h3 className="text-lg font-semibold text-text">Identifying Issues from Logs</h3>
              <div className="mt-4 space-y-4">
                <div>
                  <p className="text-sm font-medium text-text">High Latency:</p>
                  <p className="mt-1 text-sm text-muted">
                    Compare <code>http_latency_ms</code> with <code>provider_latency_ms</code>. If provider_latency_ms is high, the upstream provider is slow. If the difference is large, there may be network issues or policy evaluation overhead.
                  </p>
                </div>
                <div>
                  <p className="text-sm font-medium text-text">Budget Issues:</p>
                  <p className="mt-1 text-sm text-muted">
                    Look for <code>reason=budget_exceeded</code> in policy_block logs. Check <code>est_cost_usd</code> values to understand spending patterns.
                  </p>
                </div>
                <div>
                  <p className="text-sm font-medium text-text">Cache Performance:</p>
                  <p className="mt-1 text-sm text-muted">
                    Monitor <code>cache_hit</code> vs <code>cache_hit=false</code> ratio. Low hit rates may indicate cache TTL is too short or requests are too varied. Check <code>cache_size</code> to see if cache is at capacity.
                  </p>
                </div>
                <div>
                  <p className="text-sm font-medium text-text">Provider Errors:</p>
                  <p className="mt-1 text-sm text-muted">
                    <code>provider_error</code> logs include <code>status</code> and <code>code</code> fields from the upstream provider. Status 429 indicates rate limiting, 401 means invalid API key, 500+ are server errors.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="mt-12">
          <h2 className="text-2xl font-semibold text-text">Performance Issues</h2>

          <div className="mt-6 space-y-8">
            <div>
              <h3 className="text-lg font-semibold text-text">Cache Hit/Miss Analysis</h3>
              <p className="mt-2 text-sm text-muted">
                Caching can significantly improve performance and reduce costs. Analyze cache effectiveness from logs.
              </p>
              <div className="mt-4 space-y-3">
                <div>
                  <p className="text-sm font-medium text-text">Low Cache Hit Rate:</p>
                  <ul className="mt-2 space-y-1 text-sm text-muted list-disc list-inside">
                    <li>Increase <code>ttl_ms</code> if requests repeat within longer timeframes</li>
                    <li>Check if <code>include_params</code> is causing cache key mismatches</li>
                    <li>Verify cache is enabled: <code>cache.enabled: true</code></li>
                    <li>Monitor <code>cache_size</code> - if at <code>max_entries</code>, increase limit</li>
                  </ul>
                </div>
                <CodeSnippet
                  title="Optimize Cache Configuration"
                  lines={[
                    'routes:',
                    '  - name: acme-chat',
                    '    cache:',
                    '      enabled: true',
                    '      ttl_ms: 60000  # Increase from 30s to 60s',
                    '      max_entries: 10000  # Increase capacity',
                    '      include_params: false  # Ignore params for broader cache hits',
                  ]}
                />
              </div>
            </div>

            <div>
              <h3 className="text-lg font-semibold text-text">Latency Troubleshooting</h3>
              <p className="mt-2 text-sm text-muted">
                High latency can come from multiple sources. Use log fields to identify the bottleneck.
              </p>
              <div className="mt-4 space-y-3">
                <div>
                  <p className="text-sm font-medium text-text">Provider Latency:</p>
                  <ul className="mt-2 space-y-1 text-sm text-muted list-disc list-inside">
                    <li>If <code>provider_latency_ms</code> is high, the upstream provider is slow</li>
                    <li>Check provider API status and rate limits</li>
                    <li>Consider using a faster model or different provider endpoint</li>
                    <li>Enable caching to avoid repeated slow calls</li>
                  </ul>
                </div>
                <div>
                  <p className="text-sm font-medium text-text">Network Latency:</p>
                  <ul className="mt-2 space-y-1 text-sm text-muted list-disc list-inside">
                    <li>Large difference between <code>http_latency_ms</code> and <code>provider_latency_ms</code> indicates network issues</li>
                    <li>Check network connectivity to provider endpoints</li>
                    <li>Consider deploying ParapetAI closer to your provider</li>
                  </ul>
                </div>
                <div>
                  <p className="text-sm font-medium text-text">Policy Evaluation:</p>
                  <ul className="mt-2 space-y-1 text-sm text-muted list-disc list-inside">
                    <li>Complex redaction patterns can add latency</li>
                    <li>Budget calculations are fast but check if multiple routes are being evaluated</li>
                    <li>Drift detection adds minimal overhead</li>
                  </ul>
                </div>
              </div>
            </div>

            <div>
              <h3 className="text-lg font-semibold text-text">Budget Exhaustion Patterns</h3>
              <p className="mt-2 text-sm text-muted">
                Understanding spending patterns helps optimize budgets and prevent unexpected blocks.
              </p>
              <div className="mt-4 space-y-3">
                <div>
                  <p className="text-sm font-medium text-text">Analyze Spending:</p>
                  <ul className="mt-2 space-y-1 text-sm text-muted list-disc list-inside">
                    <li>Review <code>est_cost_usd</code> and <code>final_cost_usd</code> in logs</li>
                    <li>Check webhook events for <code>budget_spend_today_usd</code> trends</li>
                    <li>Identify high-cost routes or models</li>
                    <li>Monitor token usage (<code>tokens_in</code> + <code>tokens_out</code>)</li>
                  </ul>
                </div>
                <div>
                  <p className="text-sm font-medium text-text">Optimize Costs:</p>
                  <ul className="mt-2 space-y-1 text-sm text-muted list-disc list-inside">
                    <li>Enable caching for repeated requests (cache hits have <code>final_cost_usd: 0</code>)</li>
                    <li>Use smaller models for non-critical tasks</li>
                    <li>Set appropriate <code>max_tokens</code> limits to cap output costs</li>
                    <li>Monitor and adjust daily budgets based on actual usage</li>
                  </ul>
                </div>
              </div>
            </div>

            <div>
              <h3 className="text-lg font-semibold text-text">Retry Behavior Understanding</h3>
              <p className="mt-2 text-sm text-muted">
                Retries can mask transient errors but add latency. Understand when and how retries occur.
              </p>
              <div className="mt-4 space-y-3">
                <div>
                  <p className="text-sm font-medium text-text">Retry Triggers:</p>
                  <ul className="mt-2 space-y-1 text-sm text-muted list-disc list-inside">
                    <li>Retries only occur on configured status codes: 429, 500, 502, 503, 504</li>
                    <li>Check <code>retry_count</code> in webhook events to see retry attempts</li>
                    <li>Retries use exponential backoff with jitter</li>
                    <li>Total retry time is capped by <code>max_elapsed_ms</code></li>
                  </ul>
                </div>
                <div>
                  <p className="text-sm font-medium text-text">Optimize Retries:</p>
                  <ul className="mt-2 space-y-1 text-sm text-muted list-disc list-inside">
                    <li>For rate limits (429), increase <code>base_ms</code> for longer backoff</li>
                    <li>Reduce <code>max_attempts</code> if retries are causing excessive latency</li>
                    <li>Monitor <code>retry_count</code> to identify problematic routes</li>
                    <li>Consider disabling retries for non-critical routes</li>
                  </ul>
                </div>
                <CodeSnippet
                  title="Retry Configuration"
                  lines={[
                    'routes:',
                    '  - name: acme-chat',
                    '    retries:',
                    '      max_attempts: 3  # Total attempts (initial + 2 retries)',
                    '      base_ms: 500  # Longer backoff for rate limits',
                    '      jitter: true  # Add randomness to prevent thundering herd',
                    '      retry_on: [429, 500, 502, 503, 504]',
                    '      max_elapsed_ms: 5000  # Cap total retry time',
                  ]}
                />
              </div>
            </div>
          </div>
        </section>

        <section className="mt-12">
          <p className="text-sm text-muted">
            Still having issues? Review the <Link to="/docs/api" className="underline">API Reference</Link> for response formats, check <Link to="/docs/config" className="underline">Configuration</Link> options, or consult <Link to="/docs/security" className="underline">Security</Link> documentation.
          </p>
        </section>

        <FAQ items={faqItems} />
      </div>
    </>
  );
};

export default DocsTroubleshooting;

