import type { FC } from 'react';
import CodeSnippet from '../components/ui/CodeSnippet';

const DocsSecurity: FC = () => {
  return (
    <div className="mx-auto max-w-6xl px-4 py-16 sm:py-24">
      <header className="max-w-3xl">
        <h1 className="text-4xl font-semibold tracking-tight text-text sm:text-5xl">Security</h1>
        <p className="mt-4 text-base leading-7 text-muted">
          ParapetAI implements multiple layers of security to protect your configuration, secrets, and API access. This document describes our security practices and encryption systems.
        </p>
      </header>

      <section className="mt-12 space-y-12">
        <div>
          <h2 className="text-2xl font-semibold text-text">Configuration Encryption</h2>
          <p className="mt-4 text-sm leading-7 text-muted">
            Configuration files are encrypted using AES-256-GCM before being passed to the runtime. The encrypted bootstrap contains all route definitions, provider keys, service tokens, and policy settings.
          </p>
          <div className="mt-6 space-y-4">
            <div>
              <h3 className="text-lg font-semibold text-text">Encryption Algorithm</h3>
              <ul className="mt-3 space-y-2 text-sm text-muted list-disc list-inside">
                <li><strong>Algorithm:</strong> AES-256-GCM (Galois/Counter Mode)</li>
                <li><strong>Key Size:</strong> 256 bits (32 bytes)</li>
                <li><strong>IV/Nonce:</strong> 12 bytes, randomly generated per encryption</li>
                <li><strong>Authentication Tag:</strong> 16 bytes</li>
                <li><strong>Additional Authenticated Data (AAD):</strong> "parapet:v1"</li>
              </ul>
            </div>
            <div>
              <h3 className="text-lg font-semibold text-text">Master Key</h3>
              <p className="mt-3 text-sm text-muted">
                The master key is a 32-byte value encoded as base64url. It must be kept secret and stored securely. The CLI can generate a new master key, or you can provide your own.
              </p>
              <CodeSnippet
                title="Master key format"
                lines={[
                  '# Generated by CLI:',
                  'PARAPET_MASTER_KEY=<base64url-encoded-32-bytes>',
                  '',
                  '# Example (not a real key):',
                  'PARAPET_MASTER_KEY=abcdefghijklmnopqrstuvwxyz123456',
                ]}
              />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-text">Encrypted Bootstrap Format</h3>
              <p className="mt-3 text-sm text-muted">
                The encrypted configuration is stored as a base64url-encoded JSON payload containing the ciphertext, IV, authentication tag, and metadata.
              </p>
              <CodeSnippet
                title="Bootstrap payload structure"
                lines={[
                  '{',
                  '  "v": 1,                    # Version',
                  '  "alg": "AES-256-GCM",      # Algorithm',
                  '  "iv": "<base64url>",       # Initialization vector',
                  '  "ct": "<base64url>",       # Ciphertext',
                  '  "tag": "<base64url>"       # Authentication tag',
                  '}',
                ]}
              />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-text">Security Properties</h3>
              <ul className="mt-3 space-y-2 text-sm text-muted list-disc list-inside">
                <li><strong>Confidentiality:</strong> Configuration data is encrypted and cannot be read without the master key</li>
                <li><strong>Integrity:</strong> GCM mode provides authenticated encryption, detecting any tampering</li>
                <li><strong>Forward Secrecy:</strong> Each encryption uses a unique IV, ensuring different ciphertexts for identical plaintexts</li>
                <li><strong>Versioning:</strong> The payload includes a version field to support future algorithm migrations</li>
              </ul>
            </div>
          </div>
        </div>

        <div>
          <h2 className="text-2xl font-semibold text-text">Authentication</h2>
          <p className="mt-4 text-sm leading-7 text-muted">
            All API requests require Bearer token authentication. Service tokens map to specific tenants and allowed routes, enforcing strict access control.
          </p>
          <div className="mt-6 space-y-4">
            <div>
              <h3 className="text-lg font-semibold text-text">Bearer Token Authentication</h3>
              <p className="mt-3 text-sm text-muted">
                Clients must include a valid service token in the Authorization header. The runtime validates the token and enforces route-level access control.
              </p>
              <CodeSnippet
                title="Authentication header"
                lines={[
                  'Authorization: Bearer <service_token>',
                ]}
              />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-text">Service Token Management</h3>
              <ul className="mt-3 space-y-2 text-sm text-muted list-disc list-inside">
                <li>Service tokens are generated by the CLI or read from environment variables</li>
                <li>Each service token is associated with a tenant and a list of allowed routes</li>
                <li>Tokens are stored in the encrypted bootstrap and never exposed in logs</li>
                <li>If a token is compromised, regenerate it and rebuild the configuration</li>
              </ul>
            </div>
            <div>
              <h3 className="text-lg font-semibold text-text">Access Control</h3>
              <ul className="mt-3 space-y-2 text-sm text-muted list-disc list-inside">
                <li>Tokens without a valid service mapping are rejected</li>
                <li>Requests to routes not in the service's allowed_routes are blocked</li>
                <li>Model drift protection ensures only configured models can be called</li>
              </ul>
            </div>
          </div>
        </div>

        <div>
          <h2 className="text-2xl font-semibold text-text">Secret Management</h2>
          <p className="mt-4 text-sm leading-7 text-muted">
            Provider API keys and webhook secrets are stored in an in-memory vault at runtime. Secrets are never logged or exposed in error messages.
          </p>
          <div className="mt-6 space-y-4">
            <div>
              <h3 className="text-lg font-semibold text-text">Vault Storage</h3>
              <ul className="mt-3 space-y-2 text-sm text-muted list-disc list-inside">
                <li>Secrets are stored in memory only, never persisted to disk</li>
                <li>Provider keys are indexed by route name: <code>route:&lt;name&gt;:provider_key</code></li>
                <li>Webhook secrets are indexed by route name: <code>route:&lt;name&gt;:webhook_secret</code></li>
                <li>Secrets are populated from the decrypted bootstrap during runtime initialization</li>
              </ul>
            </div>
            <div>
              <h3 className="text-lg font-semibold text-text">Secret Resolution</h3>
              <p className="mt-3 text-sm text-muted">
                During configuration build, secrets are resolved from environment variables using the <code>ENV:NAME</code> reference format. The CLI prompts for missing secrets or reads them from the environment.
              </p>
            </div>
          </div>
        </div>

        <div>
          <h2 className="text-2xl font-semibold text-text">Data Redaction</h2>
          <p className="mt-4 text-sm leading-7 text-muted">
            ParapetAI can detect and redact sensitive data in request payloads before forwarding to providers. This prevents accidental exposure of PII, API keys, and other sensitive information.
          </p>
          <div className="mt-6 space-y-4">
            <div>
              <h3 className="text-lg font-semibold text-text">Built-in Patterns</h3>
              <ul className="mt-3 space-y-2 text-sm text-muted list-disc list-inside">
                <li><code>email</code> - Email addresses</li>
                <li><code>api_key</code> - API keys and secrets</li>
                <li><code>ip</code> - IPv4 addresses</li>
                <li><code>phone</code> - Phone numbers</li>
              </ul>
            </div>
            <div>
              <h3 className="text-lg font-semibold text-text">Custom Patterns</h3>
              <p className="mt-3 text-sm text-muted">
                You can define custom regex patterns using <code>re:pattern</code> syntax or slash-delimited regex with flags.
              </p>
              <CodeSnippet
                title="Redaction configuration example"
                lines={[
                  'policy:',
                  '  redaction:',
                  '    mode: warn              # warn (scrub) or block (reject)',
                  '    patterns:',
                  '      - email',
                  '      - api_key',
                  '      - re:secret\\d+',
                  '      - /credit-card-\\d{4}/i',
                ]}
              />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-text">Redaction Modes</h3>
              <ul className="mt-3 space-y-2 text-sm text-muted list-disc list-inside">
                <li><strong>warn:</strong> Scrubs detected patterns with placeholders like <code>[REDACTED_EMAIL]</code> and forwards the request</li>
                <li><strong>block:</strong> Rejects the request entirely if sensitive data is detected</li>
                <li><strong>off:</strong> Disables redaction (not recommended for production)</li>
              </ul>
            </div>
          </div>
        </div>

        <div>
          <h2 className="text-2xl font-semibold text-text">Webhook Signing</h2>
          <p className="mt-4 text-sm leading-7 text-muted">
            All webhook events are signed with HMAC-SHA256 to ensure authenticity and integrity. Receivers should verify signatures before processing events.
          </p>
          <div className="mt-6 space-y-4">
            <div>
              <h3 className="text-lg font-semibold text-text">Signature Format</h3>
              <p className="mt-3 text-sm text-muted">
                Webhook requests include an <code>X-Parapet-Signature</code> header with the HMAC-SHA256 signature of the raw JSON body.
              </p>
              <CodeSnippet
                title="Webhook signature header"
                lines={[
                  'X-Parapet-Signature: sha256=<hex-digest>',
                ]}
              />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-text">Verification</h3>
              <p className="mt-3 text-sm text-muted">
                Receivers should compute the HMAC-SHA256 of the raw request body using the webhook secret and compare it with the signature header.
              </p>
              <CodeSnippet
                title="Webhook verification example (Node.js)"
                lines={[
                  'import crypto from "node:crypto";',
                  '',
                  'function verifyParapetSignature(rawBody, signatureHeader, secret) {',
                  '  const expected = crypto',
                  '    .createHmac("sha256", secret)',
                  '    .update(rawBody, "utf8")',
                  '    .digest("hex");',
                  '  const provided = signatureHeader.replace(/^sha256=/, "");',
                  '  return crypto.timingSafeEqual(',
                  '    Buffer.from(expected, "hex"),',
                  '    Buffer.from(provided, "hex")',
                  '  );',
                  '}',
                ]}
              />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-text">Security Considerations</h3>
              <ul className="mt-3 space-y-2 text-sm text-muted list-disc list-inside">
                <li>Always use timing-safe comparison to prevent timing attacks</li>
                <li>Verify signatures before processing webhook payloads</li>
                <li>Store webhook secrets securely and rotate them periodically</li>
                <li>Use HTTPS endpoints for webhook receivers</li>
              </ul>
            </div>
          </div>
        </div>

        <div>
          <h2 className="text-2xl font-semibold text-text">Policy Enforcement</h2>
          <p className="mt-4 text-sm leading-7 text-muted">
            Multiple policy layers protect against unauthorized usage, cost overruns, and model drift.
          </p>
          <div className="mt-6 space-y-4">
            <div>
              <h3 className="text-lg font-semibold text-text">Token Limits</h3>
              <ul className="mt-3 space-y-2 text-sm text-muted list-disc list-inside">
                <li><strong>max_tokens_in:</strong> Maximum input tokens per request</li>
                <li><strong>max_tokens_out:</strong> Maximum output tokens (caps the request's max_tokens parameter)</li>
                <li>Requests exceeding limits are rejected before forwarding to providers</li>
              </ul>
            </div>
            <div>
              <h3 className="text-lg font-semibold text-text">Budget Controls</h3>
              <ul className="mt-3 space-y-2 text-sm text-muted list-disc list-inside">
                <li>Per-route daily budgets with micro-dollar precision</li>
                <li>Per-tenant daily spend caps</li>
                <li>Cost estimation before requests to prevent overruns</li>
                <li>Budget reservations and final settlement after completion</li>
              </ul>
            </div>
            <div>
              <h3 className="text-lg font-semibold text-text">Model Drift Protection</h3>
              <ul className="mt-3 space-y-2 text-sm text-muted list-disc list-inside">
                <li><strong>drift_strict:</strong> Blocks requests for models not explicitly configured</li>
                <li>Exact model matching within allowed routes</li>
                <li>Optional drift detection for observability (flags anomalies without blocking)</li>
              </ul>
            </div>
          </div>
        </div>

        <div>
          <h2 className="text-2xl font-semibold text-text">Telemetry Security</h2>
          <p className="mt-4 text-sm leading-7 text-muted">
            Telemetry data is stored locally in SQLite and never transmitted to external services unless explicitly configured via webhooks.
          </p>
          <div className="mt-6 space-y-4">
            <div>
              <h3 className="text-lg font-semibold text-text">Local Storage</h3>
              <ul className="mt-3 space-y-2 text-sm text-muted list-disc list-inside">
                <li>All telemetry is stored in <code>/data/parapet-telemetry.db</code> on the host filesystem</li>
                <li>Data remains in your infrastructure and is never sent to ParapetAI</li>
                <li>Database uses HKDF-derived encryption keys from the master key</li>
                <li>Telemetry includes policy decisions, costs, tokens, and drift flags</li>
              </ul>
            </div>
            <div>
              <h3 className="text-lg font-semibold text-text">Data Minimization</h3>
              <ul className="mt-3 space-y-2 text-sm text-muted list-disc list-inside">
                <li>Prompt snippets are optional and only included if explicitly configured</li>
                <li>Webhook events can be filtered by type (policy_decision, provider_error, etc.)</li>
                <li>No sensitive data is logged in telemetry by default</li>
              </ul>
            </div>
          </div>
        </div>

        <div>
          <h2 className="text-2xl font-semibold text-text">Best Practices</h2>
          <div className="mt-6 space-y-4">
            <div>
              <h3 className="text-lg font-semibold text-text">Key Management</h3>
              <ul className="mt-3 space-y-2 text-sm text-muted list-disc list-inside">
                <li>Store the master key in a secure secret manager (e.g., AWS Secrets Manager, HashiCorp Vault)</li>
                <li>Never commit master keys or service tokens to version control</li>
                <li>Rotate master keys periodically and rebuild configurations</li>
                <li>Use separate master keys for different environments (dev, staging, production)</li>
              </ul>
            </div>
            <div>
              <h3 className="text-lg font-semibold text-text">Runtime Security</h3>
              <ul className="mt-3 space-y-2 text-sm text-muted list-disc list-inside">
                <li>Run the container as a non-root user</li>
                <li>Mount the <code>/data</code> volume with appropriate permissions</li>
                <li>Use network policies to restrict container network access</li>
                <li>Enable redaction in production to prevent data leaks</li>
                <li>Set appropriate budget limits to prevent cost overruns</li>
              </ul>
            </div>
            <div>
              <h3 className="text-lg font-semibold text-text">Monitoring</h3>
              <ul className="mt-3 space-y-2 text-sm text-muted list-disc list-inside">
                <li>Monitor webhook delivery failures</li>
                <li>Review telemetry for drift violations and budget exhaustion</li>
                <li>Set up alerts for policy blocks and authentication failures</li>
                <li>Regularly audit service token usage and rotate unused tokens</li>
              </ul>
            </div>
          </div>
        </div>

        <div className="rounded-lg border-[3px] border-border bg-surface p-6">
          <h2 className="text-2xl font-semibold text-text">Security Contact</h2>
          <p className="mt-4 text-sm leading-7 text-muted">
            If you discover a security vulnerability in ParapetAI, please report it responsibly. We take security seriously and will respond promptly to valid reports.
          </p>
          <div className="mt-6">
            <a
              href="mailto:security@parapetai.com"
              className="inline-flex items-center rounded-none border-[3px] border-border bg-surface px-4 py-2 text-sm font-semibold text-text shadow-md transition-all duration-200 hover:bg-surface/90 hover:-translate-y-0.5 hover:shadow-lg active:translate-y-0 active:shadow-sm"
            >
              security@parapetai.com
            </a>
          </div>
          <p className="mt-4 text-xs text-muted">
            Please include details about the vulnerability, steps to reproduce, and potential impact. We appreciate responsible disclosure and will work with you to address any issues.
          </p>
        </div>
      </section>
    </div>
  );
};

export default DocsSecurity;


